module.exports = {
  secret: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5MzY3MjU3OCwiaWF0IjoxNjkzNjcyNTc4fQ.mM2tovpDEKqHxRz_kHH6AfrBdSahl4NSjzm35NRBZNY"
};
